### ISSUE TITLE
Missing `dataset_smiles_qm9.pkl` file 

### ISSUE THREAD

**Issue by Srilok** [croningp/electrondensity2#1]
Hello, 

Thank you for this really interesting work. 

It looks like the `dataset_smiles_qm9.pkl` file is missing. The path is hardcoded in line 200 of `qm9.py`

I get the following error when I try to run `generate_dataset.py`

```
with open("/home/nvme/juanma/Data/ED/dataset_smiles_qm9.pkl", 'rb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/nvme/juanma/Data/ED/dataset_smiles_qm9.pkl'
```

Could you please provide this file? 

Thank you

**Comment by thephet** [comment]
Hi there. I am one of the authors. will fix this asap

**Comment by thephet** [comment]
Hi @Srilok 

Can you get the last version of the code? I just pushed it into Github. I recreated everything from scratch in a new computer, and it worked fine. Please note the new information in the readme.md file. Particularly, to create the conda environment, use "conda env create -f environmentTF10.yml"

Also be careful when creating the new dataset, because it can take days. See the comment I added to readme.md

**Comment by Srilok** [comment]
Works now. Thank you!
